baseURL = "/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Wahana Sarana Informatika"


[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/font-awesome/css/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/magnafic-popup/magnific-popup.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js"
[[params.plugins.js]]
link = "plugins/waypoint/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/magnafic-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/tweenmax/TweenMax.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"

# Main Menu
  [[menu.main]]
    name = "Kontak"
    url = "#contact"
    weight = 1
  [[menu.main]]
    name = "Layanan"
    url = "#service"
    weight = 2
  [[menu.main]]
    name = "Produk"
    url = "#portfolio"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4
  [[menu.main]]
    name = "Tentang"
    url = "#about"
    weight = 5

[[menu.sosmet]]
name = "Facebook"
#icon = "fa-facebook-official"
URL = "https://www.facebook.com/wsijogja.my.id/"
[[menu.sosmet]]
name = "Instagram"
#icon = "fa-instagram-square"
URL = "https://www.instagram.com/wsijogja.my.id/"
[[menu.sosmet]]
name = "Tokopedia"
#icon = "fa-tokopedia-square"
URL = "https://www.tokopedia.com/wsijogja.my.id/"
[[menu.sosmet]]
name = "Bukalapak"
#icon = "fa-bukalapak-square"
URL = "https://www.bukalapak.com/u/wsijogja.my.id/"

# footer menu
[[menu.footer]]
name = "Blog"
URL = "blog"
weight = 1

[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 2

[[menu.footer]]
name = "Terms & Conditions"
URL = "terms-conditions"
weight = 3

[[menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 4



[params]
	blogPageURL = "blog"
	contactLink = "contact"
	copyright = "All right reserved copyright © Portio 2020"
	footerLogo = "images/contact/widget-logo.png"
	formspreeURL = "YOUR FORMSPREE URL"
	googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
	logo = "images/site-navigation/logo.png"
[params.address]
	address = "Daguran RT.119, Trimurti, Srandakan, Bantul, Yogyakarta."
	email = "service@wsijogja.my.id"
	openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
	phone = "+(85)7010 350 60"

